version: '3.1'

services:
    php:
        image: maciejslawik/php7-fpm-xdebug:7.1
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
        links:
            - rabbitmq
            - redis
            - mongodb
    nginx:
        image: maciejslawik/nginx:latest
        ports:
            - ${NGINX_PORT}:80
        links:
            - php
        volumes:
            - ./docker/vhost/:/etc/nginx/sites-available
            - .:/var/www/html
    redis:
        image: bitnami/redis:latest
        ports:
            - ${REDIS_PORT}:6379
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - redis_data:/bitnami
    mongodb:
        image: bitnami/mongodb:latest
        ports:
            - ${MONGODB_PORT}:27017
        environment:
            - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        volumes:
            - ./docker/data/mongodb:/bitnami
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - ${RABBITMQ_MANAGEMENT_PORT}:15672
          - ${RABBITMQ_MAIN_PORT}:5672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
volumes:
    redis_data:

